---
- name: Install and start nginx
  hosts: all
  become: true
  tasks:
    - name: Install nginx
      apt:
        name: nginx
        state: latest

    - name: Start nginx
      service:
        name: nginx
        state: started
        enabled: true

    - name: Create nginx config file
      template:
        src: templates/nginx.conf.j2
        dest: /etc/nginx/sites-enabled/default

    - name: Get nginx version
      command: nginx -v
      register: nginx_version
      
    - name: Extract nginx version
      set_fact:
      nginx_version: "{{ nginx_version_output.stdout | regex_search('nginx/([0-9.]+)') }}"

    - name: Print nginx version
      debug:
        var: nginx_version.stdout_lines

